### ISSUE TITLE
Missing Argument Validation in `Relation` Implementations

### ISSUE THREAD

**Issue by lhpaoletti** [AnastasiyaAD/01_uebung_7#1]
The `IstPartnerstadtVon1` and `IstPartnerstadtVon3` implementations of `Relation` are missing argument validation. Here's where it's required in the assignment:

> Überlegen Sie sich auch, wie bei Instanzbildungen für die Typklasse Relation die verschiedenen Funktionen mit Werten umgehen sollen, die die Mengeneigenschaft der Relationskomponenten verletzen. Kommentieren Sie Ihre Entwurfsentscheidung knapp, aber aussagekräftig.

**Comment by AnastasiyaAD** [comment]
können wir einfach kommentieren, dass keine zusätzliche Argumentüberprüfung erforderlich ist, da sie bereits für MT1 und MT3 implementiert ist
<img width="822" alt="Снимок экрана 2024-12-06 в 12 57 40" src="https://github.com/user-attachments/assets/2c849d56-60b4-40da-b546-f218a03b5358">
